######################## default configuration ####################
baseURL: /
title: Kisanii
theme: hugo-theme-massively
paginate: 6
summaryLength: 10
appinsights_instrumentationkey: ""
defaultContentLanguage: de
disableLanguages:
  - fr # desable language from here
params:
  backgroundPath: images/bio.jpg


outputs:
  home:
    - HTML
    - RSS
markup:
  goldmark:
    renderer:
      unsafe: true
disableKinds:
  - taxonomy
  - taxonomyTerm
  - section
