######################## default configuration ####################
baseURL: /
title: Kisanii
theme: hugo-theme-massively
pagination:
  pagerSize: 6
summaryLength: 10
appinsights_instrumentationkey: ""
defaultContentLanguage: de
disableLanguages:
  - fr # desable language from here
params:
  backgroundPath: images/bio.jpg
  favicon: favicon.ico
# Below parameters can be set to override default post settings
# [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = true
#     paginationPages = 2
#     showFirstLast = false

outputs:
  home:
    - HTML
    - RSS
markup:
  goldmark:
    renderer:
      unsafe: true
disableKinds:
  - taxonomy
  - section
