######################## default configuration ####################
baseURL: /
title: Kisanii
theme: hugo-theme-copper
paginate: 6
summaryLength: 10
appinsights_instrumentationkey: ""
defaultContentLanguage: de
disableLanguages:
  - en # desable language from here
outputs:
  home:
    - HTML
    - RSS
markup:
  goldmark:
    renderer:
      unsafe: true