de:
  languageName: Deutsch
  languageCode: de-ch
  contentDir: content
  weight: 1
  footer_content: 
  title_404: Nicht gefunden
  text_404: Wir konnten die angefragte Seite nicht finden.
  button_404: Zurück zu Home
  copyright: Entwickelt von Thomas

en:
  languageName: English
  languageCode: en-en
  contentDir: content
  weight: 2
  footer_content: Footer test text in English
  title_404: Not Found
  text_404: Not abel to find this site...
  button_404: back to home
  copyright: Developed by Thomas